### ISSUE TITLE
Odd Rendering issue with Rotational Compressor

### ISSUE THREAD

**Issue by MuteTiefling** [Lgmrszd/CompressedCreativity#22]
Version: compressedcreativity-1.19.2-0.1.5

Seems like there's a semi transparent part rendering when the item is in hand. it's not present when placed in world. 

Easier to see than describe, so here's a video: https://streamable.com/8vx6gn

**Comment by MuteTiefling** [comment]
Oh, just noticed it renders on the item form if dropped in world too.

**Comment by Lgmrszd** [comment]
Yeah, Item Model is a bit broken, fixed one will be in next update but I can just put fixed model in a resource pack so you could add that in modpack for example

**Comment by Lgmrszd** [comment]
Fixed in 0.1.6!
