### ISSUE TITLE
Suggestion: Better JEI coverage

### ISSUE THREAD

**Issue by MuteTiefling** [Lgmrszd/CompressedCreativity#23]
Checking Uses for the Air Blowers should bring the player to the same JEI pages as checking uses on the Create Encased Fan.

Similarly, the various meshes should go straight to the appropriate tab. 

![image](https://user-images.githubusercontent.com/9543430/216786206-9c00c38a-11ee-45b6-b449-3a6b20a5bf4a.png)

All of these items could be added to the highlighted area as well so if the player gets to these by checking recipes for an item, they'll see the Compressed Creativity options as well. 

Probably wouldn't hurt to add a ponder for the the industrial air blower as well, which covers meshes. I know it seems obvious that they go there, but it's the sort of thing that will trip up less experienced players.

**Comment by Lgmrszd** [comment]
That's a great suggestions, thank you! Will implement those.

**Comment by Lgmrszd** [comment]
![image](https://user-images.githubusercontent.com/16291541/220359905-fa0a8196-290b-4e2b-93cc-bfda78cac47a.png)
Implemented in the game, will be available in next release!

**Comment by MuteTiefling** [comment]
Good stuff :D

**Comment by Lgmrszd** [comment]
Oops, closed by accident (figuring out GitHub Issues integration in IDEA), will close it once it's released

**Comment by Lgmrszd** [comment]
Implemented in 0.1.6! Sorry for taking so long :(

**Comment by MuteTiefling** [comment]
No trouble! Real life first. Hope all is well <3 and thanks for the fixes.
