### ISSUE TITLE
Not Compatable with .5.1 Create Update

### ISSUE THREAD

**Issue by CassieRoseZA** [Lgmrszd/CompressedCreativity#26]
Not Compatable with .5.1 Create Update

**Comment by Lgmrszd** [comment]
I will be working on making the mod compatible with Create vesrions >=0.5.1 soon after I finish the currently planned update

**Comment by riggyz** [comment]
Hey! I would love to help with this issue but I have never made a mod for Minecraft before. I set up an Eclipse workspace and have your repo building, but when I go to run it errors out (because of missing dependency mods). How do I fix this? 

Thanks in advance

**Comment by AdalynBlack** [comment]
I decided to do the fix myself. Fixed in #29
This is purely a test version, so some things may not work as expected

**Comment by riggyz** [comment]
@TonyGamer Nice! Could you tell me how to include the dependency mods in the when you go to build it? I want to help port another mod I use to Create 0.5.1 but I am mostly embedded dev so my Java skills are lackluster.

**Comment by AdalynBlack** [comment]
You need to update the mods.toml in the assets folder to the version range, and you need to update the mod version that it builds against in the gradle file. The exact value you need to change it to varies by mod, so I'd check the documentation of the mod to see what they say to do. If it's using cursemaven, you can find the name of the artifact for it directly on curseforge

**Comment by Lgmrszd** [comment]
New version should be out in 1-3 days

**Comment by Lgmrszd** [comment]
Ok it's actually out 8 hours ago

**Comment by XTCProbstA2** [comment]
LETS GOO!! I have been waiting for this. I just made a mod pack and was wanting this in it. Was going to be a quest base mod progression mod pack!! Ty for updating it to 5.1!
