### ISSUE TITLE
Crash when using mod with Create 0.5.1b

### ISSUE THREAD

**Issue by Branjoman** [Lgmrszd/CompressedCreativity#27]
Following on from issue #26 , Compressed Creativity crashes on startup when using the new version of Create (0.5.1b).

Crash Report: https://pastebin.com/nRa9Lx9f

Versions:
 - Create: 0.5.1b
 - Pneumaticcraft: Repressurized: 4.3.4-24
 - Compressed Creativity: 0.1.5

**Comment by Lgmrszd** [comment]
Yep, 0.5.1 introduced some changes to the code, will be working on the update soon™
Closing thise one as duplicate though
