### ISSUE TITLE
Crash after Pneumaticraft Update to 3.2.2-79

### ISSUE THREAD

**Issue by Nyuraa** [Lgmrszd/CompressedCreativity#3]
Since the Update of Pneumaticraft the game crashes on world loading

When CompressedCreativity is deactivated the world loads again.
Crash Report https://gist.github.com/Nyuraa/7cdfea83d856fb5b1e9378252bc11fbc
latest.log seems to be to big for gisthub
part of it with the Error: https://gist.github.com/Nyuraa/db018f029413d976e8f77dd4d6f0f7c4

Issue at PNC Github: https://github.com/TeamPneumatic/pnc-repressurized/issues/1003

**Comment by zachsai** [comment]
I have the same issue

**Comment by desht** [comment]
Stick with PNC 3.2.1 for now.  I will work with @Lgmrszd in the meantime to sort this out for the next CC release.

**Comment by Lgmrszd** [comment]
I'll try to release a hotfix before tomorrow, but new update with separate goggles upgrade is planned later for this week, currently working with @desht on using new PNC Upgrades API.

**Comment by Lgmrszd** [comment]
Released hotfix, using new method name (https://github.com/Lgmrszd/CompressedCreativity/releases/tag/v1.18.2-0.0.10-hf1). Proper fix is gonna be released soon, using API methods from PNC.
