### ISSUE TITLE
Meshes don't work with Create 0.5.1e 1.19.2

### ISSUE THREAD

**Issue by Snooziepup** [Lgmrszd/CompressedCreativity#34]
As of Create 0.5.1e on 1.19.2, all of the Industrial Air Blower meshes no longer function, not changing the blower's particles and not appearing as part of the respective blowing recipes in JEI.

**Comment by Lgmrszd** [comment]
Yeah I knew it would break with new Create version (they changed the way fan processing types are registered), but given the way meshes are implemented, I am surprised it doesn't crash in the first place...
