### ISSUE TITLE
[1.20.1 Suggestion] Lower forge requirement to 47.1.3

### ISSUE THREAD

**Issue by RedCraft86** [Lgmrszd/CompressedCreativity#38]
Many modders have recommended sticking to forge version 47.1.3 as anything greater is supposedly very unstable. Many mods and modpacks have decided to stick to said version of forge for that reason. So I recommend the minimum forge version requirement be lowered to 47.1.3 instead of 47.1.43, nothing seems to break from my own test recompilations of the mod with that version.

**Comment by Lgmrszd** [comment]
Oops, accidentally set requirement version same as dev environment version. Gonna change that, thanks for the heads up!
