### ISSUE TITLE
0.5.1e Crashes on startup (client side)

### ISSUE THREAD

**Issue by dxcently** [Lgmrszd/CompressedCreativity#41]
logs: https://mclo.gs/icwn5C0 (prismlauncher)
minecraft version: 1.20.1

It crashes for me client side w/ create version 0.5.1e. The server I was running this on seems to load, but it doesn't seem to work client side

**Comment by Lgmrszd** [comment]
This seems very similar to #39
Can you try out steps I described in that issue?

**Comment by Lgmrszd** [comment]
Ok closing this in favor of  #39
