### ISSUE TITLE
Air blower can't accept heat except from heatpipes.

### ISSUE THREAD

**Issue by Kevin-Marsh** [Lgmrszd/CompressedCreativity#44]
I have been playing around with the air blower and I was experimenting with trying to get it to work in 1.20. It seems that the only way that I have found is to use a piece of heat pipe attached to the heat source in order to transmit the heat. Would it be possible to amend this behavior? Eg the blaze burner directly heats the refinery above but needs a piece of heat pipe to transmit into the blower.
![2024-03-20_10 03 51](https://github.com/Lgmrszd/CompressedCreativity/assets/9076964/d6365329-037c-41e8-8ba4-fd1bf21a7f10)

**Comment by Kevin-Marsh** [comment]
Edit: Nevermind. It started working? It seems like the heat transmission is low enough from a blaze burner that it wasn't noticeable unless superheated. Sorry for your time and I am loving this mod.

**Comment by Lgmrszd** [comment]
I should probably rebalance how heating works and also make it more clear in the in-game book, so thank you for the feedback!
